// https://docusaurus.io/docs/sidebar

import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// noinspection JSUnusedGlobalSymbols
export default {
  documentation: [
    {
      type: 'autogenerated',
      dirName: 'documentation',
    },
  ],
  support: [
    {
      type: 'autogenerated',
      dirName: 'support',
    },
  ],
} satisfies SidebarsConfig;
