// https://docusaurus.io/docs/sidebar

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  documentation: [
    {
      type: "autogenerated",
      dirName: "documentation",
    },
  ],
  support: [
    {
      type: "autogenerated",
      dirName: "support",
    },
  ],
};

export default sidebars; //module.exports = sidebars;
